### ISSUE TITLE
[SDKCLI-42] Feature dependsOn value.

### ISSUE THREAD

**Issue by yoannfleurydev** [saagie/sdk#68]
At the moment, the `dependsOn` key on a feature only requires a field to be filled. But what if the feature could appear on a given value?

Take a `Select` for example, with options **Option 1** and **Option 2**.

```yaml
    - type: SELECT
      name: dataset
      label: Dataset
      required: true
      options:
        - id: opt1
          value: Option 1
        - id: opt2
          value: Option 2
    - type: TEXT
      name: username
      label: Username
      dependsOn:
        - dataset.opt1
    - type: TEXT
      name: login
      label: Login
      dependsOn:
        - dataset.opt2
```

Here, the `username` input should appear only when `opt1` **Option 1** is selected and `login` when `opt2` **Option 2** is selected.
